### ISSUE TITLE
TwitterException status code returns -1 when the Twitter API returned Http response code : 429

### ISSUE THREAD

**Issue by vamsikt** [Twitter4J/Twitter4J#328]
It seems that TwitterException retuning `status code` as `-1` when there is `429/rate limit` error from twitter.
Current behaviour: 
```
twitter4j.TwitterException: Server returned HTTP response code: 429 for URL: https://api.twitter.com/1.1/statuses/user_timeline.json?user_id=XXXX&include_my_retweet=true&since_id=1132320472118067200&max_id=1136656568005660672&count=200&include_entities=true&trim_user=1&include_ext_alt_text=true&tweet_mode=extended
	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:185)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
	at twitter4j.HttpClientBase.get(HttpClientBase.java:75)
	at twitter4j.TwitterImpl.get(TwitterImpl.java:2084)
	at twitter4j.TwitterImpl.getUserTimeline(TwitterImpl.java:163)
```
**Expected behavior:** `Status code` should be `429` instead of `-1` and also should provide `RateLimitStatus` information.

**Comment by vamsikt** [comment]
Stack Trace:
![Screen Shot 2019-06-26 at 4 26 09 PM](https://user-images.githubusercontent.com/9420290/60212422-374a1e80-982f-11e9-9232-e1bffd79388b.png)

**Comment by diekuehlung** [comment]
I agree it is just clean logging.

**Comment by 125569489** [comment]
This is limited,You can try this https://twitter.utools.me/ tel: https://t.me/Yang0619
