### ISSUE TITLE
OAuth NullPointerException

### ISSUE THREAD

**Issue by darkfrog26** [Twitter4J/Twitter4J#347]
Following the example on the website everything works until I get to `getOAuthAccessToken`:

```
java.lang.NullPointerException
  at twitter4j.HttpParameter.containsJson(HttpParameter.java:171)
  at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:129)
  at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
  at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
  at twitter4j.auth.OAuthAuthorization.getOAuthAccessToken(OAuthAuthorization.java:125)
  at twitter4j.TwitterBaseImpl.getOAuthAccessToken(TwitterBaseImpl.java:340)
```

Any feedback on how to resolve this issue?

**Comment by EsGeh** [comment]
I have the same problem. Does anyone have a hint how to solve it?
gradle-version: org.twitter4j:twitter4j-core:4.0.7

```
twitter4j.Twitter twitter = TwitterFactory.getSingleton();
twitter.setOAuthConsumer( twitter_app_token, twitter_app_secret );
RequestToken requestToken = twitter.getOAuthRequestToken();
System.out.println("Got request token.");
System.out.println("Request token: " + requestToken.getToken());
System.out.println("Request token secret: " + requestToken.getTokenSecret());
AccessToken accessToken = twitter.getOAuthAccessToken(requestToken);
```
The last line throws:

```
java.lang.NullPointerException
 error: java.io.IOException: java.lang.NullPointerException
        at twitter4j.HttpParameter.containsJson(HttpParameter.java:171)
        at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:129)
        at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
        at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
        at twitter4j.auth.OAuthAuthorization.getOAuthAccessToken(OAuthAuthorization.java
        at twitter4j.auth.OAuthAuthorization.getOAuthAccessToken(OAuthAuthorization.java
        at twitter4j.TwitterBaseImpl.getOAuthAccessToken(TwitterBaseImpl.java:359)
        at com.example.twitter_parser_java.Twitter.init(Twitter.java:46)
        at com.example.twitter_parser_java.TwitterParser.main(TwitterParser.java:12)
```

**Comment by darkfrog26** [comment]
The problem is that you're not passing the `oauth_verifier` value that comes back from the OAuth callback: `twitter.getOAuthAccessToken(oAuthVerifier)`
