### ISSUE TITLE
memory leak issue with filter/sample streams (OutOfMemoryError)

### ISSUE THREAD

**Issue by nlacombe42** [Twitter4J/Twitter4J#362]
I'd like your help to troubleshoot an issue that I am having right now.
I have an application that is starting a sample stream and a filter stream.
with following code:
```java
 public void saveTweetsFromSampleEnglishStreamToMysql(JobManager jobManager) {
        if (isSampleStreamRunning())
            throw new IllegalStateException("Sample stream already running");

        sampleTwitterStream = new TwitterStreamFactory().getInstance();
        var tweetStreamProcessor = new TweetStreamProcessor<>(
                this::mapToSampleEnTweetMysqlEntity,
                tweet -> true,
                tweet -> sampleEnTweetRepository.saveNewTransaction(tweet),
                jobManager);
        sampleTwitterStream.addListener(tweetStreamProcessor);

        sampleTwitterStream.sample("en");
    }

    public void saveTweetsFromFilterStreamToMysql(JobManager jobManager) {
        if (isFilterStreamRunning())
            throw new IllegalStateException("Filter stream already running");

        var tweetStreamProcessor = new TweetStreamProcessor<>(
                this::mapToFilterTweetMysqlEntity,
                tweet -> !tweet.isRetweet() && hasAtLeastOneMentionWhichIsNotTrump(tweet),
                tweet -> filterTweetRepository.saveNewTransaction(tweet),
                jobManager);
        
        filterTwitterStream = new TwitterStreamFactory().getInstance();
        filterTwitterStream.addListener(tweetStreamProcessor);

        var query = String.join(",", tweetService.getTwitterFilterStreamSearchTerms());

        jobManager.logInfo("Filter query: " + query);

        filterTwitterStream.filter(query);
    }
```
`TweetStreamProcessor` is a class I created that extends `StatusAdapter`

when I run this code in a container in kubernetes, the application keeps allocating more object on the heap until I get the following stacktrace:
```
2020-09-23T15:07:20.435985210Z Exception in thread "Twitter Stream consumer /  [2][Receiving stream]" java.lang.OutOfMemoryError: Java heap space
2020-09-23T15:07:22.675606323Z 	at java.base/java.util.Arrays.copyOf(Arrays.java:3536)
2020-09-23T15:07:29.800117902Z 	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:227)
2020-09-23T15:07:29.800155482Z 	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:746)
2020-09-23T15:07:29.800162303Z 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:227)
2020-09-23T15:07:29.800166974Z 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:360)
2020-09-23T15:07:29.800172023Z 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
2020-09-23T15:07:29.800177409Z 	at twitter4j.StatusStreamBase.handleNextElement(StatusStreamBase.java:75)
2020-09-23T15:07:30.192220405Z 	at twitter4j.StatusStreamImpl.next(StatusStreamImpl.java:56)
2020-09-23T15:07:30.589816918Z 	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:586)
2020-09-23T15:07:33.099983182Z Exception in thread "Twitter4J Async Dispatcher[0]" Exception in thread "Twitter Stream consumer /  [1][Receiving stream]" java.lang.OutOfMemoryError: Java heap space
2020-09-23T15:07:34.927015829Z java.lang.OutOfMemoryError: Java heap space
2020-09-23T15:07:36.078109258Z 	at java.base/java.util.Arrays.copyOfRange(Arrays.java:3821)
2020-09-23T15:07:36.675096892Z 	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:767)
2020-09-23T15:07:37.457241416Z 	at java.base/java.lang.StringBuilder.toString(StringBuilder.java:447)
2020-09-23T15:07:37.847761939Z 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:361)
2020-09-23T15:07:38.408351273Z 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
2020-09-23T15:07:38.408388159Z 	at twitter4j.StatusStreamBase.handleNextElement(StatusStreamBase.java:75)
2020-09-23T15:07:41.842110008Z 	at twitter4j.StatusStreamImpl.next(StatusStreamImpl.java:56)
2020-09-23T15:07:41.842148713Z 	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:586)
2020-09-23T15:07:42.244803317Z Exception in thread "Twitter4J Async Dispatcher[1]" java.lang.OutOfMemoryError: Java heap space
2020-09-23T15:08:00.709791324Z 2020-09-23 15:07:57,961 ERROR [Catalina-utility-2    ] [DirectJDKLog        ] - Error processing async timeouts                                             @org.apache.coyote.http11.Http11NioProtocol 
2020-09-23T15:08:00.709840142Z java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
2020-09-23T15:08:00.709847237Z 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
2020-09-23T15:08:00.709852867Z 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
2020-09-23T15:08:00.709873256Z 	at org.apache.coyote.AbstractProtocol.startAsyncTimeout(AbstractProtocol.java:615)
2020-09-23T15:08:00.709879385Z 	at org.apache.coyote.AbstractProtocol$1.run(AbstractProtocol.java:598)
2020-09-23T15:08:00.709884561Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-09-23T15:08:00.709904259Z 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
2020-09-23T15:08:00.709909121Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
2020-09-23T15:08:00.709913870Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2020-09-23T15:08:00.709918535Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2020-09-23T15:08:00.709922935Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2020-09-23T15:08:00.709927587Z 	at java.base/java.lang.Thread.run(Thread.java:832)
2020-09-23T15:08:00.709932190Z Caused by: java.lang.OutOfMemoryError: Java heap space
2020-09-23T15:08:33.241580939Z Exception in thread "Twitter4J Async Dispatcher[2]" java.lang.OutOfMemoryError: Java heap space
```

I did a heap dump and it looks like there is a threadpoolexecutor which holds a linkedblockingqueue which holds thousands of StatusStreamBase object.
I tried looking quickly through your code but I am not sure what could cause this.
I am not sure weither if it's me misuing the library or an issue in the library itself.
From what I see I am writing similar code than "9. Streaming API" here: http://twitter4j.org/en/code-examples.html

**Comment by rzo1** [comment]
Might be too many unprocessed tweets stored in the queue - we had similar issues while running a long term twitter study. 

You can process them in parallel by specifying the async number of threads in the config.

**Comment by nlacombe42** [comment]
thanks for pointing out the threads config I did not know it existed.
I also ended up assuming that was the issue (too many messages in the queue).
but I ended up deciding to write my own custom twitter api client and stopped using twitter4j, since it looks like it is no longuer maintaned.

**Comment by rzo1** [comment]
Sadly, this is true. Might become alive with the new V2 API (or not) again.
