### ISSUE TITLE
TwitterStream class no more working as twitter forcing to use V2 version API

### ISSUE THREAD

**Issue by parmar049** [Twitter4J/Twitter4J#389]
I am using twitter4j latest dependency 4.0.7 to stream some sample tweets for testing purposes. I am getting the below error while trying to stream tweets

**Code I am using :**

public static void filteredStream() {
        StatusListener listener = new StatusListener() {
            @Override
            public void onException(Exception e) {
                e.printStackTrace();
            }
            @Override
            public void onStatus(Status status) {
                System.out.println(status.getUser().getName() + " : " + status.getText());
            }
            @Override
            public void onDeletionNotice(StatusDeletionNotice statusDeletionNotice) {
                System.out.println("Got a status deletion notice id:" + statusDeletionNotice.getStatusId());
            }
            @Override
            public void onTrackLimitationNotice(int numberOfLimitedStatuses) {
                System.out.println("Got track limitation notice:" + numberOfLimitedStatuses);
            }
            @Override
            public void onScrubGeo(long userId, long upToStatusId) {
                System.out.println("Got scrub_geo event userId:" + userId + " upToStatusId:" + upToStatusId);
            }
            @Override
            public void onStallWarning(StallWarning stallWarning) {
                System.out.println("Got stall warning:" + stallWarning);
            }
        };
        TwitterStream twitterStream = new TwitterStreamFactory().getInstance();
        twitterStream.addListener(listener);
        twitterStream.sample();
    }

**Error I am Getting ::** 

403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following).
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 403 
Please use V2 filtered and sample volume stream as alternatives
</title>
</head>
<body>
<h2>HTTP ERROR: 403</h2>
<p>Problem accessing '/1.1/statuses/sample.json?stall_warnings=true'. Reason:
<pre>    
Please use V2 filtered and sample volume stream as alternatives
</pre>
</body>
</html>

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=4d13a6ae or
	http://www.google.co.jp/search?q=d6626d63
TwitterException{exceptionCode=[4d13a6ae-d6626d63], statusCode=403, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.7}
	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:170)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
	at twitter4j.HttpClientBase.get(HttpClientBase.java:75)
	at twitter4j.TwitterStreamImpl.getSampleStream(TwitterStreamImpl.java:201)
	at twitter4j.TwitterStreamImpl$4.getStream(TwitterStreamImpl.java:170)
	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:570)

**Comment by valerioditinno** [comment]
+ 1

**Comment by suyashjoshi** [comment]
Hi @parmar049 mind submitting a pull request to the project with the updated code that supports v2 API ? Much apprecaited.

**Comment by koshishrijal** [comment]
+1

**Comment by gride29** [comment]
It is a core feature that needs to be implemented, if anybody has code that will transfer TwitterStream from v1.1 to v2.0, please submit a pull request or paste it here.

**Comment by conradwt** [comment]
@parmar049 What needs to change to support Twitter API v2.0?  I haven't programmed in Java for some time now but I'll definitely give it a shot because Twitter is recommending that all developers move to Twitter API v2.  Next, I also saw that [takke](https://github.com/takke/twitter4j-v2) has created a Twitter API v2 package add-on for this one.

**Comment by gride29** [comment]
@conradwt He did, however this package doesn't support filtered streams, which is one of the key features of twitter4j.

**Comment by conradwt** [comment]
@gride29 Yes, you're correct.  After research, it looks like [takke](https://github.com/takke/twitter4j-v2/issues/1) has no plans of supporting it at this time.
