### ISSUE TITLE
TwitterStream API throws Exception

### ISSUE THREAD

**Issue by armdev** [Twitter4J/Twitter4J#403]
With latest version of twitter4j I got an exception: 

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=ee74468e or
	http://www.google.co.jp/search?q=9eaf216e
TwitterException{exceptionCode=[ee74468e-9eaf216e 69215812-3735082c 69215812-3735081d], statusCode=-1, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.1.0}
	at twitter4j.HttpClient.handleRequest(HttpClient.java:191)
	at twitter4j.HttpClient.request(HttpClient.java:72)
	at twitter4j.HttpClient.get(HttpClient.java:279)
	at twitter4j.TwitterStreamImpl.getSampleStream(TwitterStreamImpl.java:209)
	at twitter4j.TwitterStreamImpl$4.getStream(TwitterStreamImpl.java:180)
	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:387)
Caused by: java.io.FileNotFoundException: https://stream.twitter.com/1.1/statuses/sample.json?stall_warnings=true
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at twitter4j.HttpResponse.<init>(HttpResponse.java:54)
	at twitter4j.HttpClient.handleRequest(HttpClient.java:155)

with the same credentials timeline API works fine.

**Comment by zorrobiwan** [comment]
v1.1 statuses/filter endpoint has been depreciated by Twitter last month

https://twittercommunity.com/t/announcing-the-deprecation-of-v1-1-statuses-filter-endpoint/182960

You should use v2

**Comment by armdev** [comment]
Thanks @zorrobiwan , but only twitter4j.v1.TwitterStream  available in twitter4j. I am using oAuthAccessToken & oAuthConsumer

**Comment by armdev** [comment]
Thanks @zorrobiwan

**Comment by zorrobiwan** [comment]
Note that starting next April 29, you will need an enterprise license to use this endpoint ($42k per month) 😬
